// Autogenerated using mud system-types
export const systemToId = {
  ERC721PetSystem: "system.ERC721.pet",
  ListingBuySystem: "system.ListingBuy",
  ListingSellSystem: "system.ListingBuy",
  ListingSetSystem: "system.ListingSet",
  MerchantCreateSystem: "system.MerchantCreate",
  NodeCreateSystem: "system.NodeCreate",
  OperatorSetSystem: "system.operator.set",
  ProductionCollectSystem: "system.ProductionCollect",
  ProductionStartSystem: "system.ProductionStart",
  ProductionStopSystem: "system.ProductionStop",
};

export const idToSystem = {
  "system.ERC721.pet": "ERC721PetSystem",
  "system.ListingBuy": "ListingBuySystem",
  "system.ListingBuy": "ListingSellSystem",
  "system.ListingSet": "ListingSetSystem",
  "system.MerchantCreate": "MerchantCreateSystem",
  "system.NodeCreate": "NodeCreateSystem",
  "system.operator.set": "OperatorSetSystem",
  "system.ProductionCollect": "ProductionCollectSystem",
  "system.ProductionStart": "ProductionStartSystem",
  "system.ProductionStop": "ProductionStopSystem",
};
  