// Autogenerated using mud system-types
import { ListingBuySystem } from "./ethers-contracts/ListingBuySystem";
import { ListingSellSystem } from "./ethers-contracts/ListingSellSystem";
import { ListingSetSystem } from "./ethers-contracts/ListingSetSystem";
import { MerchantCreateSystem } from "./ethers-contracts/MerchantCreateSystem";
 
export type SystemTypes = {
  "system.ListingBuy": ListingBuySystem;
  "system.ListingSell": ListingSellSystem;
  "system.ListingSet": ListingSetSystem;
  "system.MerchantCreate": MerchantCreateSystem;
};
