// Autogenerated using mud system-types
export const systemToId = {
  ERC721PetSystem: "system.ERC721.pet",
  ListingBuySystem: "system.ListingBuy",
  ListingSellSystem: "system.ListingSell",
  ListingSetSystem: "system.ListingSet",
  MerchantCreateSystem: "system.MerchantCreate",
  NodeCreateSystem: "system.NodeCreate",
  ProductionStartSystem: "system.ProductionStart",
};

export const idToSystem = {
  "system.ERC721.pet": "ERC721PetSystem",
  "system.ListingBuy": "ListingBuySystem",
  "system.ListingSell": "ListingSellSystem",
  "system.ListingSet": "ListingSetSystem",
  "system.MerchantCreate": "MerchantCreateSystem",
  "system.NodeCreate": "NodeCreateSystem",
  "system.ProductionStart": "ProductionStartSystem",
};
  