// Autogenerated using mud system-types
import ERC721PetSystem from "../abi/ERC721PetSystem.json";
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import ListingSetSystem from "../abi/ListingSetSystem.json";
import MerchantCreateSystem from "../abi/MerchantCreateSystem.json";
import NodeCreateSystem from "../abi/NodeCreateSystem.json";
import ProductionStartSystem from "../abi/ProductionStartSystem.json";

export const SystemAbis = {
  "system.ERC721.pet": ERC721PetSystem.abi,
  "system.ListingBuy": ListingBuySystem.abi,
  "system.ListingSell": ListingSellSystem.abi,
  "system.ListingSet": ListingSetSystem.abi,
  "system.MerchantCreate": MerchantCreateSystem.abi,
  "system.NodeCreate": NodeCreateSystem.abi,
  "system.ProductionStart": ProductionStartSystem.abi,
};
