// Autogenerated using mud system-types
import EquipModifierPetSystem from "../abi/EquipModifierPetSystem.json";
import ERC721PetSystem from "../abi/ERC721PetSystem.json";
import InitSystem from "../abi/InitSystem.json";
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import ListingSetSystem from "../abi/ListingSetSystem.json";
import MerchantCreateSystem from "../abi/MerchantCreateSystem.json";
import NameOperatorSystem from "../abi/NameOperatorSystem.json";
import NamePetSystem from "../abi/NamePetSystem.json";
import NodeCreateSystem from "../abi/NodeCreateSystem.json";
import OperatorMoveSystem from "../abi/OperatorMoveSystem.json";
import OperatorSetSystem from "../abi/OperatorSetSystem.json";
import PetFoodSystem from "../abi/PetFoodSystem.json";
import PetMetadataSystem from "../abi/PetMetadataSystem.json";
import PetSetOperatorSystem from "../abi/PetSetOperatorSystem.json";
import ProductionCollectSystem from "../abi/ProductionCollectSystem.json";
import ProductionStartSystem from "../abi/ProductionStartSystem.json";
import ProductionStopSystem from "../abi/ProductionStopSystem.json";
import RoomCreateSystem from "../abi/RoomCreateSystem.json";
import TradeAcceptSystem from "../abi/TradeAcceptSystem.json";
import TradeAddToSystem from "../abi/TradeAddToSystem.json";
import TradeCancelSystem from "../abi/TradeCancelSystem.json";
import TradeConfirmSystem from "../abi/TradeConfirmSystem.json";
import TradeInitiateSystem from "../abi/TradeInitiateSystem.json";

export const SystemAbis = {
  "system.Pet.EquipModifierSystem": EquipModifierPetSystem.abi,
  "system.ERC721.pet": ERC721PetSystem.abi,
  "system.Init": InitSystem.abi,
  "system.ListingBuy": ListingBuySystem.abi,
  "system.ListingSell": ListingSellSystem.abi,
  "system.ListingSet": ListingSetSystem.abi,
  "system.MerchantCreate": MerchantCreateSystem.abi,
  "system.NameOperator": NameOperatorSystem.abi,
  "system.NamePet": NamePetSystem.abi,
  "system.NodeCreate": NodeCreateSystem.abi,
  "system.OperatorMove": OperatorMoveSystem.abi,
  "system.OperatorSet": OperatorSetSystem.abi,
  "system.Pet.Food": PetFoodSystem.abi,
  "system.ERC721.metadata": PetMetadataSystem.abi,
  "system.PetSetOperator": PetSetOperatorSystem.abi,
  "system.ProductionCollect": ProductionCollectSystem.abi,
  "system.ProductionStart": ProductionStartSystem.abi,
  "system.ProductionStop": ProductionStopSystem.abi,
  "system.RoomCreate": RoomCreateSystem.abi,
  "system.TradeAccept": TradeAcceptSystem.abi,
  "system.TradeAddTo": TradeAddToSystem.abi,
  "system.TradeCancel": TradeCancelSystem.abi,
  "system.TradeConfirm": TradeConfirmSystem.abi,
  "system.TradeInitiate": TradeInitiateSystem.abi,
};
