// Autogenerated using mud system-types
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import ListingSetSystem from "../abi/ListingSetSystem.json";
import MerchantCreateSystem from "../abi/MerchantCreateSystem.json";

export const SystemAbis = {
  "system.ListingBuy": ListingBuySystem.abi,
  "system.ListingSell": ListingSellSystem.abi,
  "system.ListingSet": ListingSetSystem.abi,
  "system.MerchantCreate": MerchantCreateSystem.abi,
};
