// Autogenerated using mud system-types
import { ERC721PetSystem } from "./ethers-contracts/ERC721PetSystem";
import { ListingBuySystem } from "./ethers-contracts/ListingBuySystem";
import { ListingSellSystem } from "./ethers-contracts/ListingSellSystem";
import { ListingSetSystem } from "./ethers-contracts/ListingSetSystem";
import { MerchantCreateSystem } from "./ethers-contracts/MerchantCreateSystem";
import { NodeCreateSystem } from "./ethers-contracts/NodeCreateSystem";
import { ProductionCollectSystem } from "./ethers-contracts/ProductionCollectSystem";
import { ProductionStartSystem } from "./ethers-contracts/ProductionStartSystem";
import { ProductionStopSystem } from "./ethers-contracts/ProductionStopSystem";
 
export type SystemTypes = {
  "system.ERC721.pet": ERC721PetSystem;
  "system.ListingBuy": ListingBuySystem;
  "system.ListingSell": ListingSellSystem;
  "system.ListingSet": ListingSetSystem;
  "system.MerchantCreate": MerchantCreateSystem;
  "system.NodeCreate": NodeCreateSystem;
  "system.ProductionCollect": ProductionCollectSystem;
  "system.ProductionStart": ProductionStartSystem;
  "system.ProductionStop": ProductionStopSystem;
};
