// Autogenerated using mud system-types
import { ERC721PetSystem } from "./ethers-contracts/ERC721PetSystem";
import { ListingBuySystem } from "./ethers-contracts/ListingBuySystem";
import { ListingSellSystem } from "./ethers-contracts/ListingSellSystem";
import { ListingSetSystem } from "./ethers-contracts/ListingSetSystem";
import { MerchantCreateSystem } from "./ethers-contracts/MerchantCreateSystem";
import { NodeCreateSystem } from "./ethers-contracts/NodeCreateSystem";
import { OperatorMoveSystem } from "./ethers-contracts/OperatorMoveSystem";
import { OperatorSetSystem } from "./ethers-contracts/OperatorSetSystem";
import { PetSetOperatorSystem } from "./ethers-contracts/PetSetOperatorSystem";
import { ProductionCollectSystem } from "./ethers-contracts/ProductionCollectSystem";
import { ProductionStartSystem } from "./ethers-contracts/ProductionStartSystem";
import { ProductionStopSystem } from "./ethers-contracts/ProductionStopSystem";
import { RoomCreateSystem } from "./ethers-contracts/RoomCreateSystem";
 
export type SystemTypes = {
  "system.ERC721.pet": ERC721PetSystem;
  "system.ListingBuy": ListingBuySystem;
  "system.ListingBuy": ListingSellSystem;
  "system.ListingSet": ListingSetSystem;
  "system.MerchantCreate": MerchantCreateSystem;
  "system.NodeCreate": NodeCreateSystem;
  "system.OperatorMove": OperatorMoveSystem;
  "system.OperatorSet": OperatorSetSystem;
  "system.PetSetOperator": PetSetOperatorSystem;
  "system.ProductionCollect": ProductionCollectSystem;
  "system.ProductionStart": ProductionStartSystem;
  "system.ProductionStop": ProductionStopSystem;
  "system.RoomCreate": RoomCreateSystem;
};
