// Autogenerated using mud system-types
export const systemToId = {
  ListingBuySystem: "system.ListingBuy",
  ListingSellSystem: "system.ListingSell",
  ListingSetSystem: "system.ListingSet",
  MerchantCreateSystem: "system.MerchantCreate",
};

export const idToSystem = {
  "system.ListingBuy": "ListingBuySystem",
  "system.ListingSell": "ListingSellSystem",
  "system.ListingSet": "ListingSetSystem",
  "system.MerchantCreate": "MerchantCreateSystem",
};
  